Ultralytics YOLOv8.2.99 ðŸš€ Python-3.12.5 torch-2.4.0 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11012MiB)
YOLOv8m summary (fused): 218 layers, 25,840,339 parameters, 0 gradients, 78.7 GFLOPs
[34m[1mval: [39m[22mScanning /mnt/data/kai/VinDr_YOLOv8_experiments/datasets/FULL_1024_brightnessEQ_FIXED/labels/test.cache... 220 im





























                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):  99%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‰| 186/188 [00
                   all       3000        220      0.208      0.338       0.14     0.0525
Ultralytics YOLOv8.2.99 ðŸš€ Python-3.12.5 torch-2.4.0 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11012MiB)
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 188/188 [00
Generating Visualizations for batch-1/1:   0%|                                                 | 0/16 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/data/kai/VinDr_YOLOv8_experiments/trainCode/validation.py", line 26, in <module>
    metrics = model.val(project = "train_VinDr_YOLOv8",
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/yolov8/lib/python3.12/site-packages/ultralytics/engine/model.py", line 636, in val
    validator(model=self.model)
  File "/home/kai/miniconda3/envs/yolov8/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/yolov8/lib/python3.12/site-packages/ultralytics/engine/validator.py", line 199, in __call__
    self.run_callbacks("on_val_end")
  File "/home/kai/miniconda3/envs/yolov8/lib/python3.12/site-packages/ultralytics/engine/validator.py", line 268, in run_callbacks
    callback(self)
  File "/home/kai/miniconda3/envs/yolov8/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/yolov8/lib/python3.12/site-packages/wandb/integration/ultralytics/callback.py", line 362, in on_val_end
    self.validation_table = plot_detection_validation_results(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/yolov8/lib/python3.12/site-packages/wandb/integration/ultralytics/bbox_utils.py", line 177, in plot_detection_validation_results
    ground_truth_data = get_ground_truth_bbox_annotations(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/yolov8/lib/python3.12/site-packages/wandb/integration/ultralytics/bbox_utils.py", line 41, in get_ground_truth_bbox_annotations
    cls_labels = batch["cls"][indices].squeeze(1).tolist()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)