Traceback (most recent call last):
  File "/home/kai/miniconda3/envs/vindr/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 517, in get_dataset
    data = check_det_dataset(self.args.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/vindr/lib/python3.12/site-packages/ultralytics/data/utils.py", line 329, in check_det_dataset
    raise FileNotFoundError(m)
FileNotFoundError:
Dataset 'model.yaml' images not found ‚ö†Ô∏è, missing path '/mnt/data/kai/Potholes_YOLOv8/datasets/5000_600_Subset/images/val'
Note dataset download directory is '/mnt/data/kai/Potholes_YOLOv8/datasets'. You can update this in '/home/kai/.config/Ultralytics/settings.yaml'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/mnt/data/kai/VinDr_YOLOv8/traintest.py", line 25, in <module>
    model.train(project = "VinDr_YOLOv8",
  File "/home/kai/miniconda3/envs/vindr/lib/python3.12/site-packages/ultralytics/engine/model.py", line 654, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/vindr/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 130, in __init__
    self.trainset, self.testset = self.get_dataset()
                                  ^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/vindr/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 521, in get_dataset
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ‚ùå {e}")) from e
RuntimeError: Dataset 'model.yaml' error ‚ùå
Dataset 'model.yaml' images not found ‚ö†Ô∏è, missing path '/mnt/data/kai/Potholes_YOLOv8/datasets/5000_600_Subset/images/val'
Note dataset download directory is '/mnt/data/kai/Potholes_YOLOv8/datasets'. You can update this in '/home/kai/.config/Ultralytics/settings.yaml'
New https://pypi.org/project/ultralytics/8.2.13 available üòÉ Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.2.8 üöÄ Python-3.12.3 torch-2.3.0 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11012MiB)
[34m[1mengine/trainer: [39m[22mtask=detect, mode=train, model=yolov8n.pt, data=model.yaml, epochs=2, time=None, patience=100, batch=16, imgsz=1024, save=True, save_period=-1, cache=False, device=[0], workers=8, project=VinDr_YOLOv8, name=TEST_YOLOv8_5000t600v_2e4, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=VinDr_YOLOv8/TEST_YOLOv8_5000t600v_2e4